security:
    encoders:
        GlobeSoft\ScrumManagerWebBundle\Entity\Account:
            algorithm: sha512
            encode_as_base64: false
            iterations: 1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        account_db:
            entity: { class: GSScrumWebBundle:Account, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login_firewall:
                pattern:    ^/account/login$
                anonymous:  ~

        secured_area:
            pattern:    ^/
            provider: account_db
            form_login:
                login_path: /account/login
                check_path: /account/login_check
            logout:
                path:   /account/logout
                target: /account/login
            anonymous: ~

    access_control:
        - { path: ^/project, roles: ROLE_USER }

        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
